#!/bin/bash

setTriggerRofi() {
  bash ~/SourceCode/rofi-emc-theme/scripts/screenRecord
}

setTakeRecord() {
  status=$(cat $HOME/.cache/screenrecord/status)
  eww="eww -c $HOME/SourceCode/eww-emc-theme"
   
  generate_filename() {
    local DIR=~/Videos
    local counter=1
    while [ -e "$DIR/$(date "+%Y-%m-%d")-at-$(date "+%k")-o'clocks-screenrecord-$(printf $counter).mkv" ]; do
      counter=$((counter + 1))
    done
    echo "$DIR/$(date "+%Y-%m-%d")-at-$(date "+%k")-o'clocks-screenrecord-$(printf $counter).mkv"
  }

  if [[ $status == "stop" ]]; then
    sh -c "$eww close shortcuts & $eww open bar"
    sh -c "echo start > $HOME/.cache/screenrecord/status"
    (
      echo "record-start"

      while [ "$(cat $HOME/.cache/screenrecord/status)" != "stop" ]; do
        sleep 1
      done

      echo "record-pause"
      echo "record-save"
      echo "quit"
    ) | simplescreenrecorder --start-hidden
  else
    sh -c "$eww close shortcuts & $eww open bar"
    sh -c "echo stop > $HOME/.cache/screenrecord/status"
  fi
}   
   
getStatus () {
  status=$(cat $HOME/.cache/screenrecord/status)
  if [[ $status == "stop" ]]; then
    echo off 
  else   
    echo on  
  fi   
}   
   
getIcon() { 
  typeSource=$(cat $HOME/.cache/screenrecord/typeSource)  

  if [[ -n $typeSource ]]; then
    echo ""
  fi
}   
   
if [[ $1 == "icon" ]]; then
  getIcon   
fi   
   
if [[ $1 == "status" ]]; then
  getStatus  
fi  
  
if [[ $1 == "set" ]]; then
  setTriggerRofi
fi

if [[ $1 == "take" ]]; then
  setTakeRecord
fi
